security:
  jwt:
    token:
      expire-length: 3600000
      secret-key: efdsfasdfdsfdsafdsfsdafdsfdsafsdfddddfdfdfdfdfdfd

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
